/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.ArrayList;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import DAO.DichVu_dao;
import Enitity.DichVu;

/**
 *
 * @author Lenovo
 */
public class QuanLyDichVu extends javax.swing.JPanel {

    /**
     * Creates new form Quanlinhanvien
     */
    public QuanLyDichVu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_madichvu = new javax.swing.JLabel();
        txt_madichvu = new javax.swing.JTextField();
        lbl_tendichvu = new javax.swing.JLabel();
        txt_tendichvu = new javax.swing.JTextField();
        btn_themdichvu = new javax.swing.JButton();
        btn_capnhatdichvu = new javax.swing.JButton();
        btn_lamoidichvu = new javax.swing.JButton();
        btn_timkiemdichvu = new javax.swing.JButton();
        cb_loaidichvu = new javax.swing.JComboBox<>();
        lbl_loaidichvu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dichvu = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÍ DỊCH VỤ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(336, 336, 336))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbl_madichvu.setText("Mã dịch vụ : ");

        lbl_tendichvu.setText("Tên dịch vụ : ");

        btn_themdichvu.setText("Tạo mới");
        btn_themdichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themdichvuActionPerformed(evt);
            }
        });

        btn_capnhatdichvu.setText("Cập nhật");
        btn_capnhatdichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatdichvuActionPerformed(evt);
            }
        });

        btn_lamoidichvu.setText("Làm mới");
        btn_lamoidichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamoidichvuActionPerformed(evt);
            }
        });

        btn_timkiemdichvu.setText("Tìm kiếm");
        btn_timkiemdichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemdichvuActionPerformed(evt);
            }
        });

        cb_loaidichvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đồ ăn", "Đồ uống", "Trang trí" }));
        cb_loaidichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_loaidichvuActionPerformed(evt);
            }
        });

        lbl_loaidichvu.setText("Loại dịch vụ : ");

        table_dichvu.setBackground(new java.awt.Color(199, 199, 231));
        String[] headers = "Mã DV;Tên dịch vụ;Loại;Số lượng;Giá".split(";");
        tableModel = new DefaultTableModel(headers, 0);
        table_dichvu.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(table_dichvu = new JTable(tableModel));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tendichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_madichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_madichvu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_loaidichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_loaidichvu, 0, 1, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addComponent(txt_tendichvu))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_timkiemdichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_capnhatdichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_lamoidichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_themdichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_capnhatdichvu)
                    .addComponent(btn_lamoidichvu)
                    .addComponent(lbl_madichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_madichvu)
                    .addComponent(lbl_loaidichvu)
                    .addComponent(cb_loaidichvu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_timkiemdichvu)
                            .addComponent(btn_themdichvu))
                        .addComponent(lbl_tendichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txt_tendichvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        
       this.fillDataIntoTable();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themdichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themdichvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_themdichvuActionPerformed

    private void btn_capnhatdichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatdichvuActionPerformed
            CapNhatDichVu framecapnhatdichvu = new CapNhatDichVu();
            framecapnhatdichvu.setVisible(true);
    }//GEN-LAST:event_btn_capnhatdichvuActionPerformed

    private void btn_lamoidichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamoidichvuActionPerformed
        fillDataIntoTable();
        txt_madichvu.setText("");
        txt_tendichvu.setText("");
    }//GEN-LAST:event_btn_lamoidichvuActionPerformed

    private void btn_timkiemdichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemdichvuActionPerformed
       search();
    }//GEN-LAST:event_btn_timkiemdichvuActionPerformed

    private void cb_loaidichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_loaidichvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_loaidichvuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capnhatdichvu;
    private javax.swing.JButton btn_lamoidichvu;
    private javax.swing.JButton btn_themdichvu;
    private javax.swing.JButton btn_timkiemdichvu;
    private javax.swing.JComboBox<String> cb_loaidichvu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_loaidichvu;
    private javax.swing.JLabel lbl_madichvu;
    private javax.swing.JLabel lbl_tendichvu;
    private javax.swing.JTable table_dichvu;
    private javax.swing.JTextField txt_madichvu;
    private javax.swing.JTextField txt_tendichvu;
    // End of variables declaration//GEN-END:variables
    private ArrayList<DichVu> dsDichVu = new ArrayList<>();
    private DichVu_dao dao= new DichVu_dao();
	private DefaultTableModel tableModel;
    
    private void fillDataIntoTable() {

    	dsDichVu.clear();
    	if (tableModel.getRowCount() > 0) {
			for (int i = tableModel.getRowCount() - 1; i > -1; i--) {
				tableModel.removeRow(i);
			}
		}
    	dsDichVu = dao.getAll();
    	for(DichVu dv: dsDichVu) {
			String[] rowData = { dv.getMaDichVu(), dv.getTenDichVu(), dv.getLoaiDichVu()
					, dv.getSoLuong()+"",dv.getGia()+""	};
			tableModel.addRow(rowData);

    	}
    	table_dichvu.setModel(tableModel);
    }
    
    private void search() {
    	String maDichVu = txt_madichvu.getText();
    	String tenDichVu = txt_tendichvu.getText();
//    	String loaiDichVu = "";
    	String loaiDichVu = (String) cb_loaidichvu.getSelectedItem();
    	dsDichVu.clear();
    	if (tableModel.getRowCount() > 0) {
			for (int i = tableModel.getRowCount() - 1; i > -1; i--) {
				tableModel.removeRow(i);
			}
		}
    	dsDichVu = dao.search(maDichVu, tenDichVu, loaiDichVu);
    	for(DichVu dv: dsDichVu) {
			String[] rowData = { dv.getMaDichVu(), dv.getTenDichVu(), dv.getLoaiDichVu()
					, dv.getSoLuong()+"",dv.getGia()+""	};
			tableModel.addRow(rowData);

    	}
    	table_dichvu.setModel(tableModel);
    }
}
